config/routes.rb
FarewellBoard2::Application.routes.draw do

  devise_for :users

  resources :users, only: [] do
    resources :messages
  end

  get "pages/slide"

  root :to => 'pages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  attr_accessible :text, :to_user_id
  belongs_to :to_user, class_name: "User"
  validates :user_id, :text, :to_user_id, presence: true
  validates :text, length: {maximum: 140}
  validates :to_user_id, uniqueness: {scope: :user_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  validates :name, presence: true

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.json
  before_filter :validate_user#, only: [:index, :new, :edit, :create, :destroy, :update]

  def index
    @messages = current_user.messages

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  #def show
  #  @message = Message.find(params[:id])

  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @message }
  #  end
  #end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.messages.build(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to user_messages_path(current_user), notice: 'Message was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to user_messages_path(current_user), notice: 'Message was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to user_messages_url }
      format.json { head :no_content }
    end
  end

  private

  def validate_user
    if current_user.id != params[:user_id].to_i
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout false, only: [:slide]
  def index
    if signed_in?
      redirect_to user_messages_path(current_user)
    end
  end

  def slide
    if signed_in?
      @users = User.all.shuffle
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "FarewellBoard2"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    -# %link(href="images/favicon.ico" rel="shortcut icon")
    -#%link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    -#%link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    -#%link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

    /
      Javascripts
      \==================================================
    = javascript_include_tag "application"
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") FarewellBoard
          .container.nav-collapse
            - if user_signed_in?
              %ul.nav.pull-right
                %li.navbar-text
                  Logged in as
                  = current_user.email
                %li
                  = link_to "Sign out", destroy_user_session_path


    .container

      .content
        .row
          .span9
            = yield
    
      %footer
        -# %p &copy; Company 2012

app/views/messages/_form.html.haml
= form_for [current_user, @message] do |f|
  -if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text, maxlength: 140, rows: 5
    %span#char-count
      = 140 - (@message.text.presence || '').length
  -# %div
  -#   Characters left:
  -# .field
  -#   = f.label :to_user_id
  -#   = f.number_field :to_user_id
  .actions
    = f.submit 'Save'
:javascript
  $('#message_text').live('keyup keydown', function(e) {
    var maxLen = 140;
    var left = maxLen - $(this).val().length;
    $('#char-count').html(left);
  });

app/views/messages/edit.html.haml
%h1= "Editing message for #{@message.to_user.name}さん"

= render 'form'

= link_to 'Back', user_messages_path(current_user)

app/views/messages/index.html.haml
%h1 My messages
%p
  -# = link_to 'New Message', new_user_message_path(current_user.id), class: "btn"
- if @messages.any?
  %table.table.table-bordered.table-condensed
    %thead
      %tr
        %th(width="70px")
        %th(width="120px") To
        %th Text
    %tbody
      - @messages.each do |message|
        %tr
          %td{:style=>'text-align: center'}
            = link_to 'Edit', edit_user_message_path(current_user, message), class: "btn"
            -# = link_to 'Destroy', user_message_path(current_user, message), :confirm => 'Are you sure?', :method => :delete
          %td= "#{message.to_user.name}さん"
          %td= message.text
- else
  %p
    No messages.

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', user_messages_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b User:
  = @message.user
%p
  %b Text:
  = @message.text
%p
  %b To user:
  = @message.to_user_id

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path

app/views/pages/index.html.haml
%h1 Welcome to Farewell Board!
- if !user_signed_in?
  %p
    = link_to "Sign in", new_user_session_path, class: "btn"
    -# or 
    -# = link_to "Sign up!", new_user_registration_path, class: "btn"
- else
  = link_to "See my messages", user_messages_path(current_user.id), class: "btn"

app/views/pages/slide.erb
<!DOCTYPE html>

<!--
  Google HTML5 slide template

  Authors: Luke Mahé (code)
           Marcin Wichary (code and design)
           
           Dominic Mazzoni (browser compatibility)
           Charles Chen (ChromeVox support)

  URL: http://code.google.com/p/html5slides/
-->

<html>
  <head>
    <title>Messages</title>

    <meta charset='utf-8'>
    <script
      src='http://html5slides.googlecode.com/svn/trunk/slides.js'></script>
  </head>

  <body style='display: none'>

    <section class='slides layout-regular template-default'>
      
    <article>
        <h1>Messages for you</h2>
    </article>
      
<% @users.each_with_index do |u,ui| %>
    <% messages = Message.find_all_by_to_user_id(u.id).shuffle %>
    <% messages.each_with_index do |m,mi| %>
        <% if mi % 7 == 0 %>
            <article class='smaller'>
            <h3>
              <%= "#{u.name}さんへ (#{mi>6?2:1}/2)" %>
            </h3>
            <ul>
        <% end %>
        <li>
            <%= m.text %>
            <%= "(#{m.user.name})" %>
        <% if (mi+1) % 7 == 0 || m == messages.last %>
            <h5>
                <%= "(#{(ui*2)+1+(mi>6?1:0)} of #{@users.count * 2})" %>
            </h5>
            </article>
        <% end %>
    <% end %>
<% end %>

    <article>
        <h1>おわり</h2>
        <p><%= link_to "最初から", pages_slide_path %></p>
    </article>
        
    </section>

  </body>
</html>